imagier/urls.py
from django.conf.urls import url
from . import views


app_name = 'imagier'

urlpatterns = [
    url(r'^category/$', views.category, name="category"),
    url(r'^subcategory/$', views.subcategory, name="subcategory"),
    url(r'^items/$', views.items, name="items"),
    url(r'^add_item/$', views.add_to_imagier, name="add_item"),
    url(r'^delete_item/$', views.del_from_imagier, name="del_item"),
    url(r'^export_pdf/$', views.export_pdf, name="export_pdf"),
    url(r'^pdf/$', views.generate_pdf, name="render_pdf"),
    url(r'^add_image/$', views.add_image, name="add_image"),
    url(r'^save_image/$', views.save_image, name="save_image"),
    url(r'^added_successfully/$', views.added_successfully, name="added_successfully"),
    url(r'^legal_notices/$', views.legal_notices, name="legal_notices"),
    url(r'^del_tempimg/$', views.del_tempimg, name="del_tempimg"),

]

imagier_project/urls.py
from django.contrib import admin
from django.urls import path, include
from imagier import views


urlpatterns = [
    path('site_admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('imagier/', include('imagier.urls', namespace='imagier')),
    path('users/', include('users.urls', namespace='users')),
]

users/urls.py
from django.conf.urls import url
from . import views


app_name = 'users'

urlpatterns = [
    url(r'^login/$', views.user_login, name="login"),
    url(r'^logout/$', views.user_logout, name="logout"),
    url(r'^save_imagier/$', views.save_imagier, name='save_imagier'),
    url(r'^favourites/$', views.favourites, name='favourites'),
    url(r'^details/$', views.details, name='details'),
    url(r'^del_fav/$', views.del_favourite, name='del_fav'),
    url(r'^create_account/$', views.create_account, name="create_account"),
]

imagier/models.py
"""Here are the 3 models we use into the app"""


from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    """Category model will contain items with many to many rs"""
    name = models.CharField(max_length=30, unique=True, null=False)
    label = models.CharField(max_length=30, unique=False, null=False)
    is_parent = models.BooleanField(default=False, null=False)
    parentcat = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name

class Item(models.Model):
    """All the items we want to display on pdf"""
    name = models.CharField(max_length=55, unique=True, null=False)
    label = models.CharField(max_length=55, unique=False, null=False)
    upper_label = models.CharField(max_length=55, unique=False, null=False)
    picture = models.URLField(blank=True, null=False, max_length=1000, unique=False)
    category = models.ManyToManyField(Category, related_name='item', blank=True)
    user = models.ManyToManyField(User, related_name='item', blank=True)

    def __str__(self):
        return self.name

    def admin_names(self):
        return ', '.join([a.admin_name for a in self.user.all()])
    admin_names.short_description = "Admin names"

class Favourites(models.Model):
    """Table to save as favourites imagiers"""
    name = models.CharField(max_length=30, unique=False, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ManyToManyField(Item, related_name='favourites')

    def __str__(self):
        return self.name

imagier/forms.py
"""All the forms we use into imagier app"""


from django import forms
from .validators import verify_image_url
from .models import Category, Item
from .constants import PDF_FONT_CHOICE


class ExportImagierForm(forms.Form):
    """Form to export pdf template"""
    required_css_class = 'img-form-list-row'

    imagier_title = forms.CharField(
        label='',
        max_length=50,
        widget=forms.TextInput(attrs={'placeholder': 'Titre de l\'imagier', 'class': 'form-font'})
    )

    file_name = forms.CharField(
        label='',
        max_length=50,
        widget=forms.TextInput(attrs={'placeholder': 'Nom du PDF', 'class': 'form-font'})
    )

    font_choice = forms.MultipleChoiceField(
        label='',
        required=False,
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'checkbox-font'}),
        choices=PDF_FONT_CHOICE
    )

class AddImageForm(forms.Form):
    """Form to add image template"""
    required_css_class = 'img-form-list-row'

    item_label = forms.CharField(
        label='',
        max_length=55,
        widget=forms.TextInput(attrs={'placeholder': 'Nom de l\'image', 'class': 'form-font'})
    )

    image_url = forms.URLField(
        label='',
        max_length=1000,
        widget=forms.TextInput(attrs={'placeholder': 'URL de l\'image', 'class': 'form-font'}),
        validators=[verify_image_url]
    )

    cat_choice = forms.ModelChoiceField(
        label='',
        queryset=Category.objects.filter(is_parent=False).order_by('name'),
        widget=forms.Select(attrs={'class': 'form-font'})
    )

    def clean(self):
        """We check if the url already exists into db only for the same cat"""
        cleaned_data = super().clean()
        item_url = cleaned_data.get("image_url")
        cat_choice = cleaned_data.get("cat_choice")
        items = Item.objects.filter(picture=item_url)
        cat = Category.objects.get(name=cat_choice)
        if any(item in cat.item.all() for item in items):
            raise forms.ValidationError("Cette image existe déjà dans la base de données")

imagier/views.py
"""Here are alls the views from imagier app"""

import os
from imagier_project.settings import BASE_DIR
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required, user_passes_test
from .models import Category, Item, Favourites
from .utils import render_to_pdf, format_name, invert_cat_name, format_file_name, format_url
from .forms import ExportImagierForm, AddImageForm


def is_school_member(user):
    """Filter user by group école"""
    return user.groups.filter(name='école').exists()

def index(request):
    """Render index template"""
    return render(request, 'imagier/index.html')

def legal_notices(request):
    """Render legal notices template"""
    return render(request, 'imagier/legal_notices.html')

def category(request):
    """Display all parent cat"""
    if request.user.is_authenticated:
        cat_list = Category.objects.filter(is_parent=True).order_by('label')
        cat_dic = {}
        for item in cat_list:
            cat_dic[item.id] = item.label

        context = {
            'cat_dic': cat_dic
        }

        return render(request, 'imagier/category.html', context)
    return HttpResponseRedirect(reverse('users:login'))

@login_required
def subcategory(request):
    """Display all subcat from parent cat choice"""
    if 'category_id' in request.GET:
        query = request.GET.get('category_id')
        cat_id = get_object_or_404(Category, id=query)
        parent_cat = Category.objects.get(id=query)
        subcat_list = Category.objects.filter(parentcat_id=cat_id).order_by('label')
        subcat_dic = {}
        for item in subcat_list:
            subcat_dic[item.id] = item.label

        context = {
            'subcat_dic': subcat_dic,
            'category_name': parent_cat.label
        }

        return render(request, 'imagier/subcategory.html', context)

    subcat_id = request.GET.get('subcat_id')
    subcat = Category.objects.get(id=subcat_id)
    parcat_id = subcat.parentcat_id
    return HttpResponseRedirect('/imagier/subcategory/?category_id={}'.format(parcat_id))

@login_required
def items(request):
    """Display all items from a subcat choice"""
    query = request.GET.get('subcat_id')
    subcat = get_object_or_404(Category, id=query)
    item_list = subcat.item.all()
    item_dic = {}
    for item in item_list:
        if len(item.user.filter(username=request.user.username)) != 0:
            item_dic[item] = True
        else:
            item_dic[item] = False

    context = {
        'item_dic': item_dic,
        'subcat': subcat,
    }

    return render(request, 'imagier/items.html', context)

@login_required
def add_to_imagier(request):
    """Add an item to temp imagier"""
    subcat_id = request.GET.get('subcat_id')
    item_id = request.GET.get('item_id')
    _item = Item.objects.get(id=item_id)
    request.user.item.add(_item)
    return HttpResponseRedirect('/imagier/items/?subcat_id={}'.format(subcat_id))

@login_required
def del_from_imagier(request):
    """Delete an item from temp imagier"""
    if 'subcat_id' in request.GET:
        subcat_id = request.GET.get('subcat_id')
        item_id = request.GET.get('item_id')
        _item = Item.objects.get(id=item_id)
        request.user.item.remove(_item)
        return HttpResponseRedirect('/imagier/items/?subcat_id={}'.format(subcat_id))

    item_id = request.GET.get('item_id')
    _item = Item.objects.get(id=item_id)
    request.user.item.remove(_item)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

@login_required
def del_tempimg(request):
    request.user.item.clear()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def export_pdf(request):
    """Display template to chose pdf name + fonts to use"""
    imagier = request.GET.get('imagier')
    if request.method == 'POST':
        form = ExportImagierForm(request.POST)
        if form.is_valid():
            # imagier_title = form.cleaned_data['imagier_title']
            file_name = form.cleaned_data['file_name']
            font_choice = form.cleaned_data['font_choice']
            return HttpResponseRedirect('{}?file_name={}&imagier={}&fontchoice={}'.format(
                reverse('imagier:render_pdf'),
                file_name, imagier,
                font_choice
            ))
    else:
        form = ExportImagierForm()

    return render(request, 'imagier/export_pdf.html', {'form': form})

# Only users from école group can add images to DB
@login_required
@user_passes_test(is_school_member)
def add_image(request):
    """Display form to add new image to DB"""
    if request.method == 'POST':
        form = AddImageForm(request.POST)
        if form.is_valid():
            item_label = form.cleaned_data['item_label']
            image_url = form.cleaned_data['image_url']
            cat_choice = form.cleaned_data['cat_choice']
            return HttpResponseRedirect('{}?item_label={}&image_url={}&cat_choice={}'.format(
                reverse('imagier:save_image'),
                item_label,
                image_url,
                cat_choice
            ))
    else:
        form = AddImageForm()
    return render(request, 'imagier/add_image.html', {'form': form})

@login_required
def added_successfully(request):
    """Confirm that item is rightly added to DB"""
    item_name = request.GET.get('item_added')

    context = {
        'item': item_name
    }

    return render(request, 'imagier/saved_successfully.html', context)

def save_image(request):
    """Save image into the DB, from add image template"""
    if request.user.is_authenticated:
        lower_label = request.GET.get('item_label').lower()
        image_url = request.GET.get('image_url')
        cat_choice = request.GET.get('cat_choice')
        cat = Category.objects.get(name=cat_choice)
        upper_label, item_name = format_name(lower_label)

        new_item = Item(
            name=item_name,
            picture=image_url,
            label=lower_label,
            upper_label=upper_label
        )
        new_item.save()
        new_item.category.add(cat)

        inverted_cat = invert_cat_name(cat.name)
        if Category.objects.filter(name=inverted_cat).exists():
            inv_cat = Category.objects.get(name=inverted_cat)
            new_item.category.add(inv_cat)

        return HttpResponseRedirect('{}?item_added={}'.format(
            reverse('imagier:added_successfully'),
            lower_label
        ))
    return HttpResponseRedirect(reverse('users:login'))

def generate_pdf(request):
    """Generate the PDF from export pdf template"""
    if request.user.is_authenticated:
        imagier = request.GET.get('imagier')
        file_name = format_file_name(request.GET.get('file_name'))
        font_choice = request.GET.get('fontchoice')
        # Items user want to display per page | 2 for V1
        items_per_page = 2
        template_name = "imagier/invoice{}.html".format(items_per_page)
        # check if export is from temp imagier or favourites
        if imagier == 'temp_imagier':
            item_list = request.user.item.all().order_by('imagier_item_user.id')
        else:
            favourite = Favourites.objects.get(id=imagier)
            item_list = favourite.item.all().order_by('imagier_favourites_item.id')
        # all_dics = self.create_dics(items_per_page, items)
        fonts_url = file_path = os.path.join(BASE_DIR, 'imagier/static/imagier/fonts/')

        formated_items = format_url(item_list)

        context = {
            "dics": formated_items,
            "font_choice": font_choice,
            "fonts_url": fonts_url,
        }

        # PDF rendering
        pdf = render_to_pdf(template_name, context)
        if pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            filename = "%s.pdf" %(file_name)
            content = "inline; filename=%s" %(filename)
            download = request.GET.get("download")
            if download:
                content = "attachment; filename='%s'" %(filename)
            response['Content-Disposition'] = content
            return response
        return HttpResponse("Not found")
    return HttpResponseRedirect(reverse('users:login'))

# def create_dics(self, items_nb, items):
#     all_dics = {}
#     for i in range(items_nb):
#         all_dics['dic{}'.format(i)] = []
#     i = 0
#     for item in items:
#         all_dics['dic{}'.format(i)].append(item)
#         i += 1
#         if i == items_nb:
#             i = 0
#     return all_dics

imagier/templates/imagier/add_image.html
{% extends 'imagier/base.html' %}
{% load static %}

{% block content %}

<header id="mainpart" class="masthead connect-img">
  <div class="container h-100">
    <div class="row h-100 align-items-center justify-content-center text-center">
      <div class="col-lg-10 align-self-end">
        <h1 class="text-uppercase text-white font-weight-bold">Ajouter un élément à la base de données</h1>
        <hr class="divider my-4">
      </div>
      <div class="col-lg-8 align-self-baseline">
        <form method="post">
          {% csrf_token %}
          <ul class="connect-list">
            {{ form.as_ul }}
          	<li class="connect-list-row"><button id='submit-button' type="submit" class="btn btn-primary btn-xl js-scroll-trigger form-ul">Valider</button></li>
          </ul>
        </form>
      </div>
    </div>
  </div>
</header>

{% endblock %}

imagier/templates/imagier/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Imagier Project</title>

  {% load static %}
  {% load auth_extras %}

  <!-- Font Awesome Icons -->
  <link href="{% static 'imagier/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>

  <!-- Plugin CSS -->
  <link href="{% static 'imagier/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

  <!-- Theme CSS - Includes Bootstrap -->
  <link href="{% static 'imagier/css/creative.css' %}" rel="stylesheet">
  <link href="{% static 'imagier/css/imagier.css' %}" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="{% url 'index' %}">PRIMAGIER</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto my-2 my-lg-0">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger cap-text">{{ request.user }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#imagier"><i class="fas fa-images"></i></a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'users:favourites' %}"><i class="fas fa-star"></i></a>
          </li>
          {% if request.user|has_group:"école" %}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'imagier:add_image' %}"><i class="fas fa-plus"></i></a>
          </li>
          {% endif %}
          {% if request.user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="/site_admin"><i class="fas fa-user-shield"></i></a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'users:logout' %}">
              <i class="fas fa-sign-out-alt"></i>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'users:login' %}">
              <i class="fas fa-sign-in-alt"></i>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  {% block content %}{% endblock %}

  {% if request.user.is_authenticated %}
  {% if request.user.item.all.exists %}
  <section id="imagier">
    <div class="container h-100">
      <div class="row h-100 align-items-center justify-content-center text-center">
        <div class="col-lg-10 align-self-end">
          <hr class="divider my-4">
          <h1 class="text-uppercase font-weight-bold">Votre imagier en cours de création</h1>
          <hr class="divider my-4">
        </div>
      </div>
    </div>
    <div class="container-fluid p-0">
      <div class="row no-gutters">
      {% for item in current_items %}
      <div class="col-lg-3 col-sm-6">
        <div class="imagier-box">
          <img class="item-pict" src="{{ item.picture }}" alt="">
          <div class="imagier-box-caption">
            <div class="item-name">{{ item.name }}</div>
            <div class="del-pict">
              <form method="get" action="{% url 'imagier:del_item' %}">
                <input type="text" name="item_id" class="hidden-field" value="{{ item.id }}">
                <button type="submit" class="img-del-btn">
                  <i class="fas fa-trash-alt"></i>
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
      </div>
    </div>
    <div class="container h-100">
      <hr class="my-2">
      <div class="row h-100 align-items-center justify-content-center text-center">
        <div class="col-lg-10 align-self-baseline">
          <form method="get" action="{% url 'imagier:export_pdf' %}">
            <a class="btn btn-primary btn-xl js-scroll-trigger mr-1" href="{% url 'imagier:del_tempimg' %}">Supprimer l'imagier</a>
            <input type="text" name="imagier" class="hidden-field" value="temp_imagier">
            <button type="submit" class="btn btn-primary btn-xl js-scroll-trigger ml-1 mr-1">Exporter en PDF</button>
            <a class="btn btn-primary btn-xl js-scroll-trigger ml-1" href="{% url 'users:save_imagier' %}">Enregistrer en favoris</a>
          </form>
        </div>
      </div>
      <hr class="my-2">
    </div>
  </section>
  {% else %}
<!--   <section id="imagier">
    <div class="container h-100">
      <div class="row h-100 align-items-center justify-content-center text-center">
        <div class="col-lg-10 align-self-end">
          <hr class="divider my-4">
          <h1 class="text-uppercase font-weight-bold">Pas d'imagier en cours de création</h1>
          <hr class="divider my-4">
        </div>
      </div>
    </div>
  </section> -->
  {% endif %}
  {% endif %}


   <!-- Footer -->
  <footer class="bg-light py-5">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 small text-center"><a class="footer-text" href="{% url 'imagier:legal_notices' %}">Mentions légales</a></div>
        <div class="col-lg-6 small text-center"><a class="footer-text" href="mailto:?to=Anais.Zeisser@ac-strasbourg.fr">Contact</a></div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'imagier/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'imagier/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'imagier/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'imagier/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'imagier/js/creative.min.js' %}"></script>

</body>

</html>

imagier/templates/imagier/category.html
{% extends 'imagier/base.html' %}
{% load static %}

{% block content %}

<header id="mainpart" class="masthead">
  <div class="container h-100">
    <div class="row h-100 align-items-center justify-content-center text-center">
      <div class="col-lg-10 align-self-end">
        <h1 class="text-uppercase text-white font-weight-bold">Sélectionnez une catégorie</h1>
        <hr class="divider my-4">
      </div>
      <div class="col-lg-12 align-self-baseline">
        <div class="row justify-content-center align-self-baseline">
          {% for key, value in cat_dic.items %}
            <div class="col-sm-2 text-center cat-item-box">
              <form method="get" class="cat-item" action="{% url 'imagier:subcategory' %}">
                <input type="text" name="category_id" class="hidden-field" value="{{ key }}">
                <button type="submit" class="submit-btn btn btn-primary btn-xl upper-text">{{ value }}</button>
              </form>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</header>

{% endblock %}

imagier/templates/imagier/favourites.html
{% extends 'imagier/base.html' %}
{% load static %}

{% block content %}

<header id="mainpart" class="masthead">
  <div class="container h-100">
    <div class="row h-100 align-items-center justify-content-center text-center">
      <div class="col-lg-10 align-self-end">
        <h1 class="text-uppercase text-white font-weight-bold">Vos imagiers favoris</h1>
        <hr class="divider my-4">
      </div>
      <div class="col-lg-12 align-self-baseline">
        <div class="row justify-content-center align-self-baseline fav">
          {% for item in favourites %}
            <div class="col-sm-2 text-center cat-item-box rad-box">
              <form method="get" class="cat-item" action="{% url 'users:details' %}">
                <input type="text" name="favourite_id" class="hidden-field" value="{{ item.id }}">
                <button type="submit" class="submit-btn btn btn-primary btn-xl upper-text">{{ item.name }}</button>
              </form>
              <div class="del-pict">
              <form method="get" action="{% url 'users:del_fav' %}">
                <input type="text" name="favourite" class="hidden-field" value="{{ item.id }}">
                <button type="submit" class="img-del-btn">
                  <i class="fas fa-trash-alt"></i>
                </button>
              </form>
            </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</header>

{% endblock %}

imagier/templates/imagier/index.html
{% extends 'imagier/base.html' %}
{% load static %}

{% block content %}
<!-- Masthead -->
<header id="mainpart" class="masthead">
  <div class="container h-100">
    <div class="row h-100 align-items-center justify-content-center text-center">
      <div class="col-lg-10 align-self-end">
        <h1 class="text-uppercase text-white font-weight-bold">Créer mes imagiers simplement et rapidement</h1>
        <hr class="divider my-4">
      </div>
      <div class="col-lg-8 align-self-baseline">
        <p class="text-white-75 font-weight-light mb-5">Création d'imagiers à but non lucratif et à usage exclusivement pédagogique</p>
        <a class="btn btn-primary btn-xl js-scroll-trigger" href="{% url 'imagier:category' %}">Créer mon imagier</a>
      </div>
    </div>
  </div>
</header>

{% endblock %}

imagier/templates/imagier/items.html
{% extends 'imagier/base.html' %}
{% load static %}

{% block content %}

<header id="mainpart" class="masthead">
  <div class="container h-100">
    <div class="row h-100 align-items-center justify-content-center text-center">
      <div class="col-lg-10 align-self-end">
        <h1 class="text-uppercase text-white font-weight-bold">Sélectionnez les éléments à ajouter à votre imagier</h1>
        <hr class="divider my-4">
        <form method="get" action="{% url 'imagier:subcategory' %}">
          <input type="text" name="subcat_id" class="hidden-field" value="{{ subcat.id }}">
          <button type="submit" class="btn btn-primary btn-xl upper-text">Retour au choix des sous-catégories</button>
        </form>
        <hr class="divider my-4">
      </div>
      <div class="col-lg-10 align-self-baseline">
        {% if item_dic|length_is:"0" %}
        <p class="text-white-75 font-weight-light mb-5">Pas encore d'éléments dans cette catégorie</p>
        {% else %}
        <div class="row justify-content-center align-self-baseline">
          {% for item, value in item_dic.items %}
            <div class="col-sm-3 text-center cat-item-box">
              <div class="cat-item bg-white">
              <div style="background-image: url('{{ item.picture }}');background-size: contain;background-repeat:no-repeat;background-position: 50% 50%;height: 790%;border-radius:30px;"></div>
              {% if value == True %}
              <form method="get" action="{% url 'imagier:del_item' %}">
                <input type="text" name="subcat_id" class="hidden-field" value="{{ subcat.id }}">
                <input type="text" name="item_id" class="hidden-field" value="{{ item.id }}">
                <button type="submit" class="item-btn btn btn-green btn-xl cap-text">{{ item.label }} (ajouté)</button>
              </form>
              {% else %}
              <form method="get" action="{% url 'imagier:add_item' %}">
                <input type="text" name="subcat_id" class="hidden-field" value="{{ subcat.id }}">
                <input type="text" name="item_id" class="hidden-field" value="{{ item.id }}">
                <button type="submit" class="item-btn btn btn-primary btn-xl cap-text">{{ item.label }}</button>
              </form>
              {% endif %}
            </div>
            </div>
          {% endfor %}
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</header>

{% endblock %}

imagier/templates/imagier/saved_successfully.html
{% extends 'imagier/base.html' %}
{% load static %}

{% block content %}

<header id="mainpart" class="masthead connect-img">
  <div class="container h-100">
    <div class="row h-100 align-items-center justify-content-center text-center">
      <div class="col-lg-10 align-self-end">
        <h1 class="text-uppercase text-white font-weight-bold">"{{ item }}" a été ajouté à la base de donnée</h1>
        <hr class="divider my-4">
      </div>
      <div class="col-lg-8 align-self-baseline">
        <a class="btn btn-primary btn-xl js-scroll-trigger" href="{% url 'imagier:add_image' %}">Ajouter un autre élément à la base de données</a>
      </div>
    </div>
  </div>
</header>

{% endblock %}

imagier/templates/imagier/subcategory.html
{% extends 'imagier/base.html' %}
{% load static %}

{% block content %}

<header id="mainpart" class="masthead">
  <div class="container h-100">
    <div class="row h-100 align-items-center justify-content-center text-center">
      <div class="col-lg-10 align-self-end">
        <h1 class="text-uppercase text-white font-weight-bold">Catégorie : {{ category_name }}</h1>
        <hr class="divider my-4">
        <h1 class="text-uppercase text-white font-weight-bold">Sélectionnez une sous-catégorie</h1>
        <hr class="divider my-4">
        <a class="btn btn-primary btn-xl js-scroll-trigger" href="{% url 'imagier:category' %}">Retour au choix des catégories</i></a>
        <hr class="divider my-4">
      </div>
      <div class="col-lg-10 align-self-baseline">
        <div class="row justify-content-center align-self-baseline">
          {% for key, value in subcat_dic.items %}
            <div class="col-sm-3 text-center cat-item-box rad-box">
              <form method="get" class="cat-item" action="{% url 'imagier:items' %}">
                <input type="text" name="subcat_id" class="hidden-field" value="{{ key }}">
                <button type="submit" class="submit-btn btn btn-primary btn-xl upper-text">{{ value }}</button>
              </form>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</header>

{% endblock %}